### ISSUE TITLE
TypeError on importing ResnetGenerator

### ISSUE THREAD

**Issue by pan1997** [minivision-ai/photo2cartoon#17]
/usr/bin/python test.py --photo_path ./images/photo_test.jpg --save_path ./images/cartoon_result.png
2020-05-05 19:57:44.377745: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from models import ResnetGenerator
  File "/home/pankaj/Learning/photo2cartoon/models/__init__.py", line 2, in <module>
    from .UGATIT_sadalin_hourglass import UgatitSadalinHourglass
  File "/home/pankaj/Learning/photo2cartoon/models/UGATIT_sadalin_hourglass.py", line 7, in <module>
    from utils import *
  File "/home/pankaj/Learning/photo2cartoon/utils/__init__.py", line 1, in <module>
    from .preprocess import Preprocess
  File "/home/pankaj/Learning/photo2cartoon/utils/preprocess.py", line 2, in <module>
    from .face_seg import FaceSeg
  File "/home/pankaj/Learning/photo2cartoon/utils/face_seg.py", line 4, in <module>
    import tensorflow as tf
  File "/usr/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 64, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/usr/lib/python3.8/site-packages/tensorflow/python/framework/framework_lib.py", line 52, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/usr/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 28, in <module>
    from tensorflow.python.framework import function
  File "/usr/lib/python3.8/site-packages/tensorflow/python/framework/function.py", line 37, in <module>
    from tensorflow.python.ops import resource_variable_ops
  File "/usr/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 41, in <module>
    from tensorflow.python.ops import gen_logging_ops
  File "/usr/lib/python3.8/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 312, in <module>
    def image_summary(tag, tensor, max_images=3, bad_color=_execute.make_tensor("""dtype: DT_UINT8 tensor_shape { dim { size: 4 } } int_val: 255 int_val: 0 int_val: 0 int_val: 255""", "bad_color"), name=None):
  File "/usr/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 229, in make_tensor
    text_format.Merge(v, pb)
  File "/usr/lib/python3.8/site-packages/google/protobuf/text_format.py", line 696, in Merge
    return MergeLines(
  File "/usr/lib/python3.8/site-packages/google/protobuf/text_format.py", line 770, in MergeLines
    return parser.MergeLines(lines, message)
  File "/usr/lib/python3.8/site-packages/google/protobuf/text_format.py", line 795, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/usr/lib/python3.8/site-packages/google/protobuf/text_format.py", line 817, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/usr/lib/python3.8/site-packages/google/protobuf/text_format.py", line 942, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/lib/python3.8/site-packages/google/protobuf/text_format.py", line 1105, in _MergeScalarField
    setattr(message, field.name, value)
TypeError: descriptor to field 'tensorflow.TensorProto.dtype' doesn't apply to 'TensorProto' object

**Comment by hao-qiang** [comment]
It seems that the main problem is 
> File "/home/pankaj/Learning/photo2cartoon/utils/face_seg.py", line 4, in
> import tensorflow as tf

Please make sure:
1. Tensorflow is installed correctly.
2. The segmentation model is put in corresponding folder.
