### ISSUE TITLE
test时的报错 IndexError

### ISSUE THREAD

**Issue by LyannaLAU** [minivision-ai/photo2cartoon#33]
Traceback (most recent call last):
File "test.py", line 59, in
cartoon = c2p.inference(img)
File "test.py", line 38, in inference
mask = face_rgba[:, :, 3][:, :, np.newaxis].copy() / 255.
IndexError: index 3 is out of bounds for axis 2 with size 3

这个要怎么解决呢？谢谢你们

**Comment by LyannaLAU** [comment]
已经解决了，打扰你们啦
