### ISSUE TITLE
ModuleNotFoundError: No module named 'face_alignment'

### ISSUE THREAD

**Issue by AlexanderKozhevin** [minivision-ai/photo2cartoon#36]
I try to run it in google colab. 
https://colab.research.google.com/drive/1kt3JpWFvmlmjv4lGQrKNNRKVoOqsw6uV?usp=sharing
But getting an error. 
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from models import ResnetGenerator
  File "/content/photo2cartoon/models/__init__.py", line 2, in <module>
    from .UGATIT_sadalin_hourglass import UgatitSadalinHourglass
  File "/content/photo2cartoon/models/UGATIT_sadalin_hourglass.py", line 7, in <module>
    from utils import *
  File "/content/photo2cartoon/utils/__init__.py", line 1, in <module>
    from .preprocess import Preprocess
  File "/content/photo2cartoon/utils/preprocess.py", line 1, in <module>
    from .face_detect import FaceDetect
  File "/content/photo2cartoon/utils/face_detect.py", line 4, in <module>
    import face_alignment
ModuleNotFoundError: No module named 'face_alignment'
```

**Comment by eliohead** [comment]
pip3 install face_alignment

**Comment by hao-qiang** [comment]
you can install face_alignment by 
> pip install face_alignment
