### ISSUE TITLE
运行test.py时报错

### ISSUE THREAD

**Issue by zhangting1994** [minivision-ai/photo2cartoon#6]
Traceback (most recent call last):
  File "test.py", line 56, in <module>
    cartoon = c2p.inference(img)
  File "test.py", line 43, in inference
    cartoon = self.net(face)[0][0]
  File "C:\ProgramData\Anaconda3\envs\gpu\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\24238\Desktop\zhangting\photo2cartoon\models\networks.py", line 120, in forward
    x = self.DecodeBlock1(x, content_features4, style_features)
  File "C:\ProgramData\Anaconda3\envs\gpu\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\24238\Desktop\zhangting\photo2cartoon\models\networks.py", line 296, in forward
    out = self.norm1(out, content_features, style_features)
  File "C:\ProgramData\Anaconda3\envs\gpu\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\24238\Desktop\zhangting\photo2cartoon\models\networks.py", line 354, in forward
    out = self.norm(x, soft_gamma, soft_beta)
  File "C:\ProgramData\Anaconda3\envs\gpu\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\24238\Desktop\zhangting\photo2cartoon\models\networks.py", line 366, in forward
    in_mean, in_var = torch.mean(input, dim=[2, 3], keepdim=True), torch.var(input, dim=[2, 3], keepdim=True)
TypeError: var(): argument 'dim' must be int, not list

**Comment by hao-qiang** [comment]
pytorch1.1之前的版本dim只接受int型，请尝试将pytorch版本更新到1.4。
