### ISSUE TITLE
Multi-GPU training, IndexError: Caught IndexError in replica 0 on device 5.

### ISSUE THREAD

**Issue by redredbluee** [minivision-ai/photo2cartoon#75]
Traceback (most recent call last):
  File "train.py", line 84, in <module>
    main()
  File "train.py", line 75, in main
    gan.train()
  File "/home/photo2cartoon/models/UGATIT_sadalin_hourglass.py", line 191, in train
    fake_A2B, _, _ = self.genA2B(real_A)
  File "/home/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in replica 0 on device 5.
Original Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/codes/photo2cartoon/models/networks.py", line 100, in forward
    gap_weight = list(self.gap_fc.parameters())[0]
IndexError: list index out of range
how to sovle it?

**Comment by zxy2020** [comment]
你好，我也遇到相同的问题，重新按照项目的指定版本安装，就成功了，我原来的是torch=1.5

I soloved it by  
                            **change my old torch=1.5 to  torch=1.4**

conda create -n minivison -y
conda activate minivison
conda install  python=3.6   tensorflow-gpu=1.14.0   pytorch=1.4    torchvision
pip install face-alignment  onnxruntime
conda install  dlib -c conda-forge

**Comment by zxy2020** [comment]
您好，邮件已收到。曾星宇
