### ISSUE TITLE
error ：    raise AttributeError(name) from None

### ISSUE THREAD

**Issue by themass** [minivision-ai/photo2cartoon#79]
save_path  ~/Downloads/test.jpg
Traceback (most recent call last):
  File "/Users/liguoqing/work/photo2cartoon/test.py", line 59, in <module>
    c2p = Photo2Cartoon()
          ^^^^^^^^^^^^^^^
  File "/Users/liguoqing/work/photo2cartoon/test.py", line 19, in __init__
    self.pre = Preprocess()
               ^^^^^^^^^^^^
  File "/Users/liguoqing/work/photo2cartoon/utils/preprocess.py", line 8, in __init__
    self.detect = FaceDetect(device, detector)  # device = 'cpu' or 'cuda', detector = 'dlib' or 'sfd'
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liguoqing/work/photo2cartoon/utils/face_detect.py", line 10, in __init__
    self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, device=device, face_detector=detector)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liguoqing/.pyenv/versions/3.11.7/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D

**Comment by colorfulandcjy0806** [comment]
It is possible to change _2D to TWO_D, which is effective in my environment.
